"""
outlook-king — generated by meta-agent.
"""

from __future__ import annotations

import logging

from dotenv import load_dotenv
from google.adk.agents import LlmAgent
from google.adk.skills import load_skill_from_dir
from google.adk.tools.skill_toolset import SkillToolset

from .config.llm import FAST_MODEL
from .config.paths import skills_dir
from .config.seed import seed_volume_if_empty
from .tools import get_tools
from .prompt.instructions import get_agent_instruction

logger = logging.getLogger(__name__)

load_dotenv()

# First-boot: copy in-repo seeds into runtime paths if they're empty
# (no-op locally; populates a deployment volume on first deploy).
seed_volume_if_empty()


def _load_skills():
    """Load every SKILL.md under skills_dir() as an ADK Skill."""
    d = skills_dir()
    skills = []
    if not d.is_dir():
        return skills
    for skill_dir in sorted(d.iterdir()):
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
            try:
                skills.append(load_skill_from_dir(skill_dir))
            except Exception as e:
                logger.warning("Skip skill %s: %s", skill_dir.name, e)
    return skills


def _build_tools():
    tools = list(get_tools())
    skills = _load_skills()
    if skills:
        tools.append(SkillToolset(skills=skills))
    return tools


root_agent = LlmAgent(
    model=FAST_MODEL,
    name="outlook_king",
    description="AI agent for Microsoft Outlook: searches, drafts, coaches, and learns the user's writing style",
    instruction=get_agent_instruction,
    tools=_build_tools(),
)
